### ISSUE TITLE
Are you aware of https://github.com/mk270/whitakers-words?

### ISSUE THREAD

**Issue by ids1024** [ArchimedesDigital/open_words#6]
https://github.com/mk270/whitakers-words is an effort to improve original words code.

A rewrite like open_words is probably a good idea (though it is not a small task), but I thought I might mention it.

**Comment by lukehollis** [comment]
Thanks, @ids1024, that is an ambitious effort to maintain his original Ada code.  This port of the original Ada to Python will be functional after building the library in the correct manner, and I'll make the API available somewhere in the near future.
